# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Imaginato' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Imaginato
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'IQKeyboardManager'
end
